### ISSUE TITLE
Fetching and Visualizing PDB Structure

### ISSUE THREAD

**Issue by RetrosynthesisAI** [bioexcel/biobb#15]
The code for the fetching and visualization of the PBD structure does not work. This is the tutorial - https://mmb.irbbarcelona.org/biobb/workflows/tutorials/vs_bs 

Issues I have identified include 

1.  The Pdb() function is not downloading any PDB files. 
2.  The Visualizing 3D structure code also does not accept a pre-defined variable: download_pdb
 
Can you please fix or send me a link to a website that contains the correct PDB files, so I can visualize any structure?

**Comment by gbayarri** [comment]
Hi, first off thanks for using the BioExcel Building Blocks. 

Can you please be more precise about the problem you are experiencing? Have you installed the tutorial following the instructions at the begin of it?

```shell
git clone https://github.com/bioexcel/biobb_wf_virtual-screening.git
cd biobb_wf_virtual-screening
conda env create -f conda_env/environment.yml
conda activate biobb_VS_tutorial
jupyter-nbextension enable --py --user widgetsnbextension
jupyter-nbextension enable --py --user nglview
jupyter-notebook biobb_wf_virtual-screening/notebooks/ebi_api/wf_vs_ebi_api.ipynb
```
Take into account that you should use Linux or macOS. If you are a Windows user, you must use the WSL for running the BIoBB's.

Regarding to the email you sent, unfortunately, at this moment we are experiencing an issue with the BioExcel Binder. I hope it will be fixed as soon as possible.

Please let me know if you have been able to execute the workflow following the instructions.

**Comment by RetrosynthesisAI** [comment]
Hi, I agree the issues are due to not using a terminal to run the above commands. I highly recommend DeepNote over Binder, it's newer and there are free plans for larger groups such as yours. If you get the chance to establish your Virtual Screening workflows on DeepNote, please let me know (mlinan@asu.edu). https://deepnote.com/

**Comment by gbayarri** [comment]
Hi, thanks for your feedback. We will take into account DeepNote for future releases.

Kind regards.
