### ISSUE TITLE
bump up python version

### ISSUE THREAD

**Issue by pgbarletta** [bioexcel/biobb#17]
Hi, I've noticed that all the biobb packages require ==3.7, which I find a bit strict. I was wondering if there're some clear incompatibilities that need to be fixed or if we can expect a change of python requirements to >=3.7 in the near term.
Thanks!

**Comment by PauAndrio** [comment]
Hi,

Yes, you can expect a change like that in the next version. The reason we are pinning the python version, is to avoid conda too long or even failed _"environment solving"_ .
