### ISSUE TITLE
API documentations wrong links

### ISSUE THREAD

**Issue by raweru** [bioexcel/biobb#22]
Hi

I believe you used wrong API docs links in the github readmes: 

For example the biobb-amber module has the wrong link: https://biobb_amber.readthedocs.io/en/latest/

The right one is https://biobb-amber.readthedocs.io/en/latest/

I think it is the same for all other modules

**Comment by gbayarri** [comment]
Hi, thanks for your feedback.

It seems that in some links (not all, actually) of the READMEs, there was the old read the docs notation. I've fixed them.

Let us know if you find something more.

Cheers!
